import os
import re
import urllib.request
import urllib.parse
import tempfile
import asyncio
import httpx
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from app.services.openai_service import generate_json_response
from app.utils.database import log_generation

# ─── Design tokens ───
BG_DARK       = RGBColor(0x0B, 0x0D, 0x17)   # deep navy
BG_CARD       = RGBColor(0x12, 0x14, 0x22)   # card surface
ACCENT        = RGBColor(0x63, 0x66, 0xF1)   # indigo-500
ACCENT_LIGHT  = RGBColor(0x81, 0x84, 0xF5)   # lighter indigo
TEXT_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)
TEXT_GRAY      = RGBColor(0x9C, 0xA3, 0xAF)   # gray-400
TEXT_MUTED     = RGBColor(0x6B, 0x72, 0x80)   # gray-500
PURPLE         = RGBColor(0xA8, 0x55, 0xF7)   # violet-500
EMERALD        = RGBColor(0x10, 0xB9, 0x81)   # emerald-500

SLIDE_WIDTH  = Inches(13.333)  # 16:9 widescreen
SLIDE_HEIGHT = Inches(7.5)

FONT_HEADING  = "Segoe UI"
FONT_BODY     = "Segoe UI"


def _set_slide_bg(slide, color):
    """Fill the slide background with a solid colour."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_shape_rect(slide, left, top, width, height, fill_color, opacity=1.0):
    """Add a filled rectangle (used for accent bars, cards, etc.)."""
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    shape.line.fill.background()  # no border
    return shape


def _set_text(text_frame, text, font_size, color, bold=False, font_name=FONT_BODY, align=PP_ALIGN.LEFT):
    """Set formatted text on the first paragraph of a text frame."""
    text_frame.clear()
    text_frame.word_wrap = True
    p = text_frame.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.font.name = font_name
    p.alignment = align


def _add_text_box(slide, left, top, width, height, text, font_size, color,
                  bold=False, font_name=FONT_BODY, align=PP_ALIGN.LEFT):
    """Add a text box with styled text and zero margins."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)
    _set_text(tf, text, font_size, color, bold, font_name, align)
    return txBox


def _add_bullet_list(slide, left, top, width, height, items, font_size=16, color=TEXT_GRAY):
    """Add a text box containing multiple bullet points with proper hanging indents."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)

    for i, item in enumerate(items):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()

        p.text = f"▸\t{item}"
        p.font.size = Pt(font_size)
        p.font.color.rgb = color
        p.font.name = FONT_BODY
        p.space_after = Pt(12)  # breathing room between points
        p.alignment = PP_ALIGN.LEFT
        
        # Proper hanging indent:
        p.left_indent = Inches(0.35)
        p.first_line_indent = Inches(-0.25)

    return txBox


def _build_title_slide(prs, title_text, subtitle_text=""):
    """Slide 0: Full-bleed title slide with accent bar."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    _set_slide_bg(slide, BG_DARK)

    # Left accent bar
    _add_shape_rect(slide, Inches(0), Inches(0), Inches(0.15), SLIDE_HEIGHT, ACCENT)

    # Title
    _add_text_box(
        slide, Inches(1.2), Inches(2.0), Inches(10.5), Inches(1.8),
        title_text, font_size=38, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING
    )

    # Subtitle
    if subtitle_text:
        _add_text_box(
            slide, Inches(1.2), Inches(4.2), Inches(10.5), Inches(0.8),
            subtitle_text, font_size=16, color=TEXT_MUTED
        )

    # Bottom accent line
    _add_shape_rect(slide, Inches(1.2), Inches(6.7), Inches(3), Inches(0.04), ACCENT)

    # Branding
    _add_text_box(
        slide, Inches(1.2), Inches(6.85), Inches(4), Inches(0.5),
        "Generated by LockIn", font_size=11, color=TEXT_MUTED
    )


def _build_content_slide(prs, slide_data, slide_num, total_slides):
    """Standard content slide with title + bullet points."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Untitled")
    points = slide_data.get("points", [])

    # Top accent bar
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)

    # Slide number badge
    _add_text_box(
        slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4),
        f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED
    )

    # Title
    _add_text_box(
        slide, Inches(0.8), Inches(0.8), Inches(11.7), Inches(0.8),
        title, font_size=26, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING
    )

    # Divider line under title
    _add_shape_rect(slide, Inches(0.8), Inches(1.75), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Bullet points
    if points:
        _add_bullet_list(
            slide, Inches(0.8), Inches(2.1), Inches(11.7), Inches(4.5),
            points, font_size=15, color=TEXT_GRAY
        )

    # Bottom branding bar
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_CARD)
    _add_text_box(
        slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35),
        "LockIn AI — Student Productivity Platform", font_size=9, color=TEXT_MUTED
    )


async def _fetch_image_for_slide_async(client: httpx.AsyncClient, image_prompt: str, max_retries: int = 2) -> str:
    """Fetch an image from pollinations.ai with retry logic for rate limits."""
    encoded_prompt = urllib.parse.quote(image_prompt)
    url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=800&height=800&nologo=true"
    
    for attempt in range(max_retries):
        try:
            response = await client.get(url, timeout=12.0, follow_redirects=True)
            if response.status_code == 200 and len(response.content) > 1000:
                fd, path = tempfile.mkstemp(suffix=".jpg")
                with os.fdopen(fd, 'wb') as f:
                    f.write(response.content)
                return path
            elif response.status_code == 429:
                wait = 2 * (attempt + 1)
                print(f"[PPT Image] Rate limited (429), waiting {wait}s before retry {attempt+1}/{max_retries}")
                await asyncio.sleep(wait)
                continue
            elif response.status_code >= 500:
                wait = 2 * (attempt + 1)
                print(f"[PPT Image] Server error ({response.status_code}), waiting {wait}s before retry {attempt+1}/{max_retries}")
                await asyncio.sleep(wait)
                continue
            else:
                print(f"[PPT Image] Unexpected status {response.status_code}")
                return None
        except Exception as e:
            print(f"[PPT Image] Attempt {attempt+1} failed: {e}")
            if attempt < max_retries - 1:
                await asyncio.sleep(2 * (attempt + 1))
            continue
    
    print(f"[PPT Image] All {max_retries} attempts exhausted for prompt: {image_prompt[:60]}...")
    return None


def _build_visual_slide(prs, slide_data, slide_num, total_slides, image_path=None):
    """Slide with content on the left and a generated image on the right."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Untitled")
    points = slide_data.get("points", [])

    # Top accent bar & Slide number
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Title
    _add_text_box(slide, Inches(0.8), Inches(0.8), Inches(5.5), Inches(0.8), title, font_size=26, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING)
    _add_shape_rect(slide, Inches(0.8), Inches(1.75), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Bullet points
    if points:
        _add_bullet_list(slide, Inches(0.8), Inches(2.1), Inches(5.5), Inches(4.5), points, font_size=14, color=TEXT_GRAY)

    # Image
    if image_path:
        try:
            # Framing box behind the image
            _add_shape_rect(slide, Inches(6.7), Inches(0.7), Inches(5.9), Inches(5.9), BG_CARD)
            # Add image to right side
            slide.shapes.add_picture(image_path, Inches(6.8), Inches(0.8), width=Inches(5.7), height=Inches(5.7))
        except Exception as e:
            print(f"Error adding picture to slide: {e}")
        finally:
            if os.path.exists(image_path):
                os.remove(image_path)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_CARD)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "LockIn — Student Productivity Platform", font_size=9, color=TEXT_MUTED)


def _build_comparison_slide(prs, slide_data, slide_num, total_slides):
    """Two-column comparison slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Comparison")
    left_points = slide_data.get("left_points", [])
    right_points = slide_data.get("right_points", [])

    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Centered Title
    _add_text_box(slide, Inches(0.8), Inches(0.8), Inches(11.7), Inches(0.8), title, font_size=26, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING, align=PP_ALIGN.CENTER)
    _add_shape_rect(slide, Inches(5.76), Inches(1.75), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Left Column
    _add_shape_rect(slide, Inches(0.8), Inches(2.1), Inches(5.6), Inches(4.5), BG_CARD)
    if left_points:
        _add_bullet_list(slide, Inches(1.1), Inches(2.4), Inches(5.0), Inches(3.9), left_points, font_size=14, color=TEXT_GRAY)

    # Right Column
    _add_shape_rect(slide, Inches(6.9), Inches(2.1), Inches(5.6), Inches(4.5), BG_CARD)
    if right_points:
        _add_bullet_list(slide, Inches(7.2), Inches(2.4), Inches(5.0), Inches(3.9), right_points, font_size=14, color=TEXT_GRAY)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_DARK)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "LockIn — Student Productivity Platform", font_size=9, color=TEXT_MUTED)


def _build_quote_slide(prs, slide_data, slide_num, total_slides):
    """Full slide large quote."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_CARD)

    quote = slide_data.get("quote", "")
    author = slide_data.get("author", "")

    # Top accent bar & Slide number
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), PURPLE)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Big Quote marks
    _add_text_box(slide, Inches(1.2), Inches(1.2), Inches(2), Inches(1.5), "“", font_size=110, color=PURPLE, bold=True, font_name="Georgia")

    # The quote
    _add_text_box(slide, Inches(1.8), Inches(2.2), Inches(9.7), Inches(3.0), f"{quote}", font_size=32, color=TEXT_WHITE, bold=False, font_name=FONT_HEADING, align=PP_ALIGN.LEFT)

    # Author
    _add_text_box(slide, Inches(1.8), Inches(5.3), Inches(9.7), Inches(1), f"— {author}", font_size=18, color=ACCENT_LIGHT, bold=True, font_name=FONT_BODY, align=PP_ALIGN.LEFT)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_DARK)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "LockIn — Student Productivity Platform", font_size=9, color=TEXT_MUTED)



def _build_closing_slide(prs, title_text):
    """Final thank-you / closing slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _set_slide_bg(slide, BG_DARK)

    _add_shape_rect(slide, Inches(0), Inches(0), Inches(0.15), SLIDE_HEIGHT, PURPLE)

    _add_text_box(
        slide, Inches(1.5), Inches(2.6), Inches(10), Inches(1.2),
        "Thank You", font_size=44, color=TEXT_WHITE, bold=True,
        font_name=FONT_HEADING, align=PP_ALIGN.LEFT
    )

    _add_text_box(
        slide, Inches(1.5), Inches(3.9), Inches(8), Inches(0.6),
        f"Presentation on: {title_text}", font_size=16, color=TEXT_MUTED
    )

    _add_shape_rect(slide, Inches(1.5), Inches(6.7), Inches(3), Inches(0.04), PURPLE)
    _add_text_box(
        slide, Inches(1.5), Inches(6.85), Inches(5), Inches(0.4),
        "Powered by LockIn AI", font_size=11, color=TEXT_MUTED
    )


async def generate_ppt_file(prompt_text: str, num_slides: int, user_id: str = "anonymous", model="openai/gpt-4o-mini") -> str:
    """
    Calls OpenAI to get structured PPT contents, compiles them into a
    professionally styled PowerPoint file and returns the local filepath.
    """
    system_prompt = f'''You are an expert presentation designer creating a professional, university-level presentation.
Topic: "{prompt_text}"
Total slides: EXACTLY {num_slides}

RULES:
1. Use a MIX of these slide types (at least 2 different types):
   - "content": Title + 4-6 bullet points. Each bullet is 1-2 clear sentences with real substance.
   - "visual": Title + 3-4 bullet points + an "image_prompt". Use visual slides sparingly (MAXIMUM 2 visual slides per presentation). The image_prompt must be a SHORT, simple description (under 15 words, e.g. "modern office workspace with dual monitors and coffee").
   - "comparison": Title + "left_points" + "right_points" (3-4 items each). Good for pros/cons, before/after, or two approaches.
   - "quote": A memorable "quote" + "author". Use sparingly (max 1).
2. Bullet points must be substantive explanations, not vague phrases.
3. Titles must be concise (3-7 words).
4. image_prompt must be SHORT and concrete — no flowery language. Example: "student studying with laptop in library" NOT "A cinematic, breathtakingly detailed ultra-wide photograph of..."
5. IMPORTANT: Generates at most 2 "visual" slides to maintain a fast and high-quality generation.

Respond ONLY with this JSON:
{{
    "presentation_title": "Concise Title",
    "slides": [
        {{
            "type": "content",
            "title": "Slide Title",
            "points": ["Point 1.", "Point 2."]
        }},
        {{
            "type": "visual",
            "title": "Slide Title",
            "points": ["Point 1.", "Point 2."],
            "image_prompt": "short concrete image description"
        }},
        {{
            "type": "comparison",
            "title": "Slide Title",
            "left_points": ["Left 1.", "Left 2."],
            "right_points": ["Right 1.", "Right 2."]
        }},
        {{
            "type": "quote",
            "quote": "The quote text.",
            "author": "Author Name"
        }}
    ]
}}
'''

    response = await generate_json_response(
        system_prompt=system_prompt,
        user_prompt=f"Generate {num_slides} highly detailed slides now.",
        model=model,
        max_tokens=6000
    )
    slides_data = response.get("slides", [])
    pres_title = response.get("presentation_title", prompt_text[:60])

    if not slides_data:
        raise ValueError("AI failed to generate structural slide data.")

    # ── Fetch visual slide images sequentially (Pollinations rate-limits to 1 queued request per IP) ──
    img_paths = {}
    async with httpx.AsyncClient(verify=False) as client:
        for idx, slide in enumerate(slides_data):
            if slide.get("type") == "visual" and slide.get("image_prompt"):
                print(f"[PPT Image] Fetching image {idx+1}: {slide['image_prompt'][:50]}...")
                path = await _fetch_image_for_slide_async(client, slide["image_prompt"])
                if path:
                    img_paths[idx] = path
                # Small delay between requests to avoid rate limiting
                await asyncio.sleep(1)

    try:
        # ── Build the presentation ──
        prs = Presentation()
        prs.slide_width = SLIDE_WIDTH
        prs.slide_height = SLIDE_HEIGHT

        # 1. Title slide
        subtitle = f"{len(slides_data)} slides  •  AI-generated study material"
        _build_title_slide(prs, pres_title, subtitle)

        # 2. Content slides
        for idx, slide_data in enumerate(slides_data, start=1):
            slide_type = slide_data.get("type", "content")
            if slide_type == "visual":
                pre_fetched_img = img_paths.get(idx - 1)
                _build_visual_slide(prs, slide_data, idx, len(slides_data), image_path=pre_fetched_img)
            elif slide_type == "comparison":
                _build_comparison_slide(prs, slide_data, idx, len(slides_data))
            elif slide_type == "quote":
                _build_quote_slide(prs, slide_data, idx, len(slides_data))
            else:
                _build_content_slide(prs, slide_data, idx, len(slides_data))

        # 3. Closing slide
        _build_closing_slide(prs, pres_title)
    finally:
        # Clean up any image files that were downloaded but not removed
        for path in img_paths.values():
            if path and os.path.exists(path):
                try:
                    os.remove(path)
                except Exception:
                    pass

    # ── Save ──
    # Absolute path to output directory in backend folder
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    OUTPUT_DIR = os.path.join(BASE_DIR, "output")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    # Sanitize filename
    safe_name = re.sub(r'[^a-zA-Z0-9_\- ]', '', pres_title)[:40].strip().replace(' ', '_')
    filename = f"presentation_{safe_name}.pptx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    prs.save(filepath)

    # Supabase Tracking (skip for guest/anonymous users)
    if user_id not in ("guest", "anonymous"):
        log_generation(
            user_id=user_id, 
            content_type="ppt_presentation", 
            content_data={"prompt": prompt_text, "num_slides": len(slides_data), "filename": filename}
        )
    
    return filepath
