import os
import re
import urllib.request
import urllib.parse
import tempfile
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from app.services.openai_service import generate_json_response
from app.utils.database import log_generation

# ─── Design tokens ───
BG_DARK       = RGBColor(0x0B, 0x0D, 0x17)   # deep navy
BG_CARD       = RGBColor(0x12, 0x14, 0x22)   # card surface
ACCENT        = RGBColor(0x63, 0x66, 0xF1)   # indigo-500
ACCENT_LIGHT  = RGBColor(0x81, 0x84, 0xF5)   # lighter indigo
TEXT_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)
TEXT_GRAY      = RGBColor(0x9C, 0xA3, 0xAF)   # gray-400
TEXT_MUTED     = RGBColor(0x6B, 0x72, 0x80)   # gray-500
PURPLE         = RGBColor(0xA8, 0x55, 0xF7)   # violet-500
EMERALD        = RGBColor(0x10, 0xB9, 0x81)   # emerald-500

SLIDE_WIDTH  = Inches(13.333)  # 16:9 widescreen
SLIDE_HEIGHT = Inches(7.5)

FONT_HEADING  = "Segoe UI"
FONT_BODY     = "Segoe UI"


def _set_slide_bg(slide, color):
    """Fill the slide background with a solid colour."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_shape_rect(slide, left, top, width, height, fill_color, opacity=1.0):
    """Add a filled rectangle (used for accent bars, cards, etc.)."""
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    shape.line.fill.background()  # no border
    return shape


def _set_text(text_frame, text, font_size, color, bold=False, font_name=FONT_BODY, align=PP_ALIGN.LEFT):
    """Set formatted text on the first paragraph of a text frame."""
    text_frame.clear()
    text_frame.word_wrap = True
    p = text_frame.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.font.name = font_name
    p.alignment = align


def _add_text_box(slide, left, top, width, height, text, font_size, color,
                  bold=False, font_name=FONT_BODY, align=PP_ALIGN.LEFT):
    """Add a text box with styled text."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    _set_text(tf, text, font_size, color, bold, font_name, align)
    return txBox


def _add_bullet_list(slide, left, top, width, height, items, font_size=16, color=TEXT_GRAY):
    """Add a text box containing multiple bullet points."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, item in enumerate(items):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()

        p.text = f"▸  {item}"
        p.font.size = Pt(font_size)
        p.font.color.rgb = color
        p.font.name = FONT_BODY
        p.space_after = Pt(10)
        p.alignment = PP_ALIGN.LEFT

    return txBox


def _build_title_slide(prs, title_text, subtitle_text=""):
    """Slide 0: Full-bleed title slide with accent bar."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    _set_slide_bg(slide, BG_DARK)

    # Left accent bar
    _add_shape_rect(slide, Inches(0), Inches(0), Inches(0.15), SLIDE_HEIGHT, ACCENT)

    # Title
    _add_text_box(
        slide, Inches(1.2), Inches(2.2), Inches(9), Inches(1.5),
        title_text, font_size=40, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING
    )

    # Subtitle
    if subtitle_text:
        _add_text_box(
            slide, Inches(1.2), Inches(3.8), Inches(8), Inches(0.8),
            subtitle_text, font_size=18, color=TEXT_MUTED
        )

    # Bottom accent line
    _add_shape_rect(slide, Inches(1.2), Inches(6.7), Inches(3), Inches(0.04), ACCENT)

    # Branding
    _add_text_box(
        slide, Inches(1.2), Inches(6.85), Inches(4), Inches(0.5),
        "Generated by ProducHub AI", font_size=11, color=TEXT_MUTED
    )


def _build_content_slide(prs, slide_data, slide_num, total_slides):
    """Standard content slide with title + bullet points."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Untitled")
    points = slide_data.get("points", [])

    # Top accent bar
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)

    # Slide number badge
    _add_text_box(
        slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4),
        f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED
    )

    # Title
    _add_text_box(
        slide, Inches(0.8), Inches(0.9), Inches(10), Inches(1),
        title, font_size=30, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING
    )

    # Divider line under title
    _add_shape_rect(slide, Inches(0.8), Inches(1.85), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Bullet points
    if points:
        _add_bullet_list(
            slide, Inches(0.8), Inches(2.3), Inches(10.5), Inches(4.5),
            points, font_size=15, color=TEXT_GRAY
        )

    # Bottom branding bar
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_CARD)
    _add_text_box(
        slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35),
        "ProducHub AI — Student Productivity Platform", font_size=9, color=TEXT_MUTED
    )


def _fetch_image_for_slide(image_prompt):
    """Fetch an image from pollinations.ai based on a prompt and return the temp file path."""
    encoded_prompt = urllib.parse.quote(image_prompt)
    url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=800&height=800&nologo=true"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            data = response.read()
            fd, path = tempfile.mkstemp(suffix=".jpg")
            with os.fdopen(fd, 'wb') as f:
                f.write(data)
            return path
    except Exception as e:
        print(f"Failed to fetch image: {e}")
        return None


def _build_visual_slide(prs, slide_data, slide_num, total_slides):
    """Slide with content on the left and a generated image on the right."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Untitled")
    points = slide_data.get("points", [])
    image_prompt = slide_data.get("image_prompt", "")

    # Top accent bar & Slide number
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Title
    _add_text_box(slide, Inches(0.8), Inches(0.9), Inches(5.5), Inches(1.5), title, font_size=30, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING)
    _add_shape_rect(slide, Inches(0.8), Inches(2.35), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Bullet points
    if points:
        _add_bullet_list(slide, Inches(0.8), Inches(2.8), Inches(5.5), Inches(4), points, font_size=15, color=TEXT_GRAY)

    # Image
    if image_prompt:
        img_path = _fetch_image_for_slide(image_prompt)
        if img_path:
            try:
                # Add image to right side
                slide.shapes.add_picture(img_path, Inches(6.8), Inches(1.0), height=Inches(5.5))
            except Exception as e:
                print(f"Error adding picture to slide: {e}")
            finally:
                if os.path.exists(img_path):
                    os.remove(img_path)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_CARD)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "ProducHub AI — Student Productivity Platform", font_size=9, color=TEXT_MUTED)


def _build_comparison_slide(prs, slide_data, slide_num, total_slides):
    """Two-column comparison slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_DARK)

    title = slide_data.get("title", "Comparison")
    left_points = slide_data.get("left_points", [])
    right_points = slide_data.get("right_points", [])

    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), ACCENT)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Centered Title
    _add_text_box(slide, Inches(0), Inches(0.9), SLIDE_WIDTH, Inches(1), title, font_size=30, color=TEXT_WHITE, bold=True, font_name=FONT_HEADING, align=PP_ALIGN.CENTER)
    _add_shape_rect(slide, Inches(5.76), Inches(1.85), Inches(1.8), Inches(0.03), ACCENT_LIGHT)

    # Left Column
    _add_shape_rect(slide, Inches(0.8), Inches(2.3), Inches(5.5), Inches(4.5), BG_CARD)
    if left_points:
        _add_bullet_list(slide, Inches(1.2), Inches(2.6), Inches(4.7), Inches(4), left_points, font_size=14, color=TEXT_GRAY)

    # Right Column
    _add_shape_rect(slide, Inches(7.0), Inches(2.3), Inches(5.5), Inches(4.5), BG_CARD)
    if right_points:
        _add_bullet_list(slide, Inches(7.4), Inches(2.6), Inches(4.7), Inches(4), right_points, font_size=14, color=TEXT_GRAY)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_DARK)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "ProducHub AI — Student Productivity Platform", font_size=9, color=TEXT_MUTED)


def _build_quote_slide(prs, slide_data, slide_num, total_slides):
    """Full slide large quote."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BG_CARD)

    quote = slide_data.get("quote", "")
    author = slide_data.get("author", "")

    # Top accent bar & Slide number
    _add_shape_rect(slide, Inches(0), Inches(0), SLIDE_WIDTH, Inches(0.06), PURPLE)
    _add_text_box(slide, Inches(0.8), Inches(0.45), Inches(1.2), Inches(0.4), f"{slide_num:02d} / {total_slides:02d}", font_size=10, color=TEXT_MUTED)

    # Big Quote marks
    _add_text_box(slide, Inches(1.0), Inches(1.5), Inches(2), Inches(2), "“", font_size=120, color=PURPLE, bold=True, font_name="Georgia")

    # The quote
    _add_text_box(slide, Inches(1.8), Inches(2.5), Inches(9.7), Inches(2.5), f"{quote}", font_size=36, color=TEXT_WHITE, bold=False, font_name=FONT_HEADING, align=PP_ALIGN.LEFT)

    # Author
    _add_text_box(slide, Inches(1.8), Inches(5.5), Inches(9.7), Inches(1), f"— {author}", font_size=20, color=ACCENT_LIGHT, bold=True, font_name=FONT_BODY, align=PP_ALIGN.LEFT)

    # Bottom branding
    _add_shape_rect(slide, Inches(0), Inches(7.15), SLIDE_WIDTH, Inches(0.35), BG_DARK)
    _add_text_box(slide, Inches(0.8), Inches(7.15), Inches(5), Inches(0.35), "ProducHub AI — Student Productivity Platform", font_size=9, color=TEXT_MUTED)



def _build_closing_slide(prs, title_text):
    """Final thank-you / closing slide."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _set_slide_bg(slide, BG_DARK)

    _add_shape_rect(slide, Inches(0), Inches(0), Inches(0.15), SLIDE_HEIGHT, PURPLE)

    _add_text_box(
        slide, Inches(1.5), Inches(2.6), Inches(10), Inches(1.2),
        "Thank You", font_size=44, color=TEXT_WHITE, bold=True,
        font_name=FONT_HEADING, align=PP_ALIGN.LEFT
    )

    _add_text_box(
        slide, Inches(1.5), Inches(3.9), Inches(8), Inches(0.6),
        f"Presentation on: {title_text}", font_size=16, color=TEXT_MUTED
    )

    _add_shape_rect(slide, Inches(1.5), Inches(6.7), Inches(3), Inches(0.04), PURPLE)
    _add_text_box(
        slide, Inches(1.5), Inches(6.85), Inches(5), Inches(0.4),
        "Powered by ProducHub AI  •  prodhub.ai", font_size=11, color=TEXT_MUTED
    )


async def generate_ppt_file(prompt_text: str, num_slides: int, user_id: str = "anonymous", model="openai/gpt-4o-mini") -> str:
    """
    Calls OpenAI to get structured PPT contents, compiles them into a
    professionally styled PowerPoint file and returns the local filepath.
    """
    system_prompt = f'''You are an expert presentation creator and master storyteller.
Create a highly engaging, comprehensive, and detailed presentation about: "{prompt_text}".
Provide EXACTLY {num_slides} slides. 

To make it engaging and highly informative, use a variety of slide types:
- "content": Standard title and 4-6 highly detailed bullet points. Each bullet MUST be 1-2 full sentences explaining the concept thoroughly, providing deep insights rather than just short phrases.
- "visual": Title, 3-4 detailed bullet points explaining core concepts, and a vivid "image_prompt" describing a relevant cinematic photo.
- "comparison": Title, and two lists ("left_points" and "right_points") comparing two concepts with in-depth explanations.
- "quote": A highly impactful "quote" and its "author" (or an insightful takeaway formatted as a quote).

Respond ONLY with a JSON object in this extremely strict schema:
{{
    "presentation_title": "Short, Punchy Presentation Title",
    "slides": [
        {{
            "type": "content|visual|comparison|quote",
            "title": "Clean, Punchy Title (for content, visual, comparison)",
            "points": ["Detailed explanatory sentence 1.", "Detailed explanatory sentence 2."],
            "left_points": ["In-depth pro 1.", "In-depth pro 2."],
            "right_points": ["In-depth con 1.", "In-depth con 2."],
            "image_prompt": "A cinematic, highly detailed photo of...",
            "quote": "The future belongs to...",
            "author": "Name"
        }}
    ]
}}
'''

    response = await generate_json_response(
        system_prompt=system_prompt,
        user_prompt=f"Generate {num_slides} highly detailed slides now.",
        model=model,
        max_tokens=6000
    )
    slides_data = response.get("slides", [])
    pres_title = response.get("presentation_title", prompt_text[:60])

    if not slides_data:
        raise ValueError("AI failed to generate structural slide data.")

    # ── Build the presentation ──
    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # 1. Title slide
    subtitle = f"{len(slides_data)} slides  •  AI-generated study material"
    _build_title_slide(prs, pres_title, subtitle)

    # 2. Content slides
    for idx, slide_data in enumerate(slides_data, start=1):
        slide_type = slide_data.get("type", "content")
        if slide_type == "visual":
            _build_visual_slide(prs, slide_data, idx, len(slides_data))
        elif slide_type == "comparison":
            _build_comparison_slide(prs, slide_data, idx, len(slides_data))
        elif slide_type == "quote":
            _build_quote_slide(prs, slide_data, idx, len(slides_data))
        else:
            _build_content_slide(prs, slide_data, idx, len(slides_data))

    # 3. Closing slide
    _build_closing_slide(prs, pres_title)

    # ── Save ──
    os.makedirs("output", exist_ok=True)
    # Sanitize filename
    safe_name = re.sub(r'[^a-zA-Z0-9_\- ]', '', pres_title)[:40].strip().replace(' ', '_')
    filename = f"presentation_{safe_name}.pptx"
    filepath = os.path.join("output", filename)
    prs.save(filepath)

    # Supabase Tracking
    log_generation(
        user_id=user_id, 
        content_type="ppt_presentation", 
        content_data={"prompt": prompt_text, "num_slides": len(slides_data), "filename": filename}
    )
    
    return filepath
